-- The Custom.lua file will be loaded by sidTools, but it will never be included in releases, so you won't accidentally overwrite any changes.
-- It can be used to add Lua code for dev purposes quick and dirty, without having to setup a whole new addon.
--
-- Below are two example that utilize the data generated by the Item Viewer (need to run /st items and scan for items first)
-- if you need any other internal functions exposed, feel free to change the code
-- and send me a copy so I can integrate it in a future update

SLASH_COMMANDS["/dumpit"] = function()
    local specialized = {}
    sidTools_SaveData.specialized = specialized
    local normaltype = {}
    sidTools_SaveData.normaltype = normaltype

    local masterList = sidTools.itemViewer.masterList
    for i = 1, #masterList do
        local data = masterList[i]
        specialized[data.specializedType] = (specialized[data.specializedType] or 0) + 1
        normaltype[data.itemType] = (normaltype[data.itemType] or 0) + 1
    end
end

SLASH_COMMANDS["/dumpfurniture"] = function()
    local masterList = sidTools.itemViewer.masterList
    sidTools_SaveData.furniture = {}
    sidTools.furniture = {}
    for i = 1, #masterList do
        local data = masterList[i]
        if(data.itemType == ITEMTYPE_FURNISHING) then
            table.insert(sidTools_SaveData.furniture, string.format("%d-%s", data.id, data.name))
            sidTools.furniture[data.id] = data.name
        end
    end
end
